variables:
  TF_VAR_region: "ap-south-1"
  ANSIBLE_HOST_KEY_CHECKING: "False"

stages:
  - prepare
  - terraform
  - ansible

prepare_ssh:
  stage: prepare
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/redis_vm_key
    - chmod 400 ~/.ssh/redis_vm_key
    - echo "public_key = \"$SSH_PUBLIC_KEY\"" > terraform/terraform.tfvars
  artifacts:
    paths:
      - ~/.ssh/redis_vm_key
      - terraform/terraform.tfvars

terraform_apply:
  stage: terraform
  image: 
    name: hashicorp/terraform:latest
    entrypoint: [""]
  before_script:
    - cd terraform
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  script:
    - terraform init
    - terraform apply -auto-approve
    - terraform output -json > ../ansible/terraform_output.json
  artifacts:
    paths:
      - ansible/terraform_output.json

redis_setup:
  stage: ansible
  image: willhallonline/ansible:latest
  before_script:
    
    - apk add --no-cache jq
    - cd ansible
    - PUBLIC_IP=$(cat terraform_output.json | jq -r .public_ip.value)
    - echo "[redis_server]" > inventory.ini
    - echo "redis ansible_host=$PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/redis_vm_key" >> inventory.ini
  script:
    - ANSIBLE_HOST_KEY_CHEKCING=False ansible-playbook -i inventory.ini redis_setup.yml

cache:
  paths:
    - terraform/.terraform 